version: "3"

services:
  my_container:
    container_name: my_container
    build:
      context: ../05/
      dockerfile: Dockerfile

  new_container:
    container_name: new_container
    image: nginx
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf